/* Query que mostra dados do cliente que comprou, o produto e o valor total */

SELECT C.ID_CLIENTE, C.NOME, C.TELEFONE, V.DATA_VENDA, 
V.VALOR_TOTAL, I.ID_PRODUTO, P.NOME
FROM CLIENTES C
INNER JOIN VENDAS  V
ON C.ID_CLIENTE = V.ID_CLIENTE
INNER JOIN [ITENS VENDAS] I
ON V.ID_VENDAS = I.ID_VENDA
INNER JOIN PRODUTOS P 
ON I.ID_PRODUTO = P.ID_PRODUTO
GO