CREATE TABLE PRODUTOS(
[ID PRODUTO] INT PRIMARY KEY,
PRODUTO VARCHAR(100),
CATEGORIA VARCHAR(30),
[PRECO DE VENDA] MONEY,
[ESTOQUE INICIAL] INT,
FABRICANTE VARCHAR(30)
)
GO

CREATE TABLE VENDAS(
[ID VENDA] INT PRIMARY KEY,
[VALOR TOTAL] MONEY,
[METODO PAGAMENTO] VARCHAR(30),
[DATA VENDA] DATE,
[ID CLIENTE] INT
)
GO

ALTER TABLE VENDAS
ADD CONSTRAINT FK_PRODUTO
FOREIGN KEY ([ID CLIENTE])
REFERENCES CLIENTES([ID CLIENTE])
GO

CREATE TABLE [ITENS VENDAS](
[ID ITEM VENDA] INT PRIMARY KEY,
[ID VENDA] INT,
[ID PRODUTO] INT,
QUANTIDADE INT,
[PRECO UNITARIO] MONEY
)
GO

ALTER TABLE [ITENS VENDAS]
ADD CONSTRAINT FK_VENDA
FOREIGN KEY([ID VENDA])
REFERENCES VENDAS([ID VENDA])
GO

ALTER TABLE [ITENS VENDAS]
ADD CONSTRAINT FK_VENDA_PRODUTO
FOREIGN KEY([ID PRODUTO])
REFERENCES PRODUTOS([ID PRODUTO])
GO
