
CREATE DATABASE NEXTPLAY

USE NEXTPLAY 

CREATE TABLE FORNECEDORES(
	ID_FORNECEDOR INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30),
	CNPJ CHAR(14) UNIQUE,
	TELEFONE VARCHAR(30),
	ID_ENDERECO INT
)
GO
