
CREATE DATABASE NEXTPLAY

USE NEXTPLAY 

CREATE TABLE FORNECEDORES(
	ID_FORNECEDOR INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30),
	CNPJ CHAR(14) UNIQUE,
	TELEFONE VARCHAR(30),
	ID_ENDERECO INT
)
GO

CREATE TABLE PRODUTOS(
    ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(60),
    DESCRICAO TEXT,
    CATEGORIA VARCHAR(30),
    PRECO MONEY,
    [QTD ESTOQUE] INT,
    MARCA VARCHAR(30)
)

CREATE TABLE CATEGORIAS(
    ID_CATEGORIAS INT IDENTITY(1,1) PRIMARY KEY,
    CATEGORIA VARCHAR(30)
)

CREATE TABLE [GASTOS MENSAIS](
    ID_GASTOS INT,
    SALARIOS MONEY,
    [COMPRA ESTOQUE] MONEY
)
GO

CREATE  TABLE CLIENTES(
    ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(60),
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(60),
    [TOTAL GASTO] MONEY,
    ID_ENDERECO INT
)
GO

ALTER TABLE CLIENTES ADD CONSTRAINT FK_ID_ENDERECO
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
GO

CREATE TABLE VENDAS(
    ID_VENDAS INT IDENTITY(1,1) PRIMARY KEY,
    [VALOR TOTAL] MONEY,
    [METODO PAGAMENTO] VARCHAR(30),
    [DATA VENDA] DATE,
    ID_CLIENTES INT
)
GO

ALTER TABLE VENDAS ADD CONSTRAINT FK_ID_CLIENTES
FOREIGN KEY(ID_CLIENTES) REFERENCES CLIENTES(ID_CLIENTE)
GO

CREATE TABLE [ITENS VENDAS](
    ID_ITEM_VENDA INT IDENTITY(1,1) PRIMARY KEY,
    ID_VENDA INT,
    ID_PRODUTO INT,
    QUANTIDADE INT,
    [PRECO UNITARIO] MONEY,
    SUBTOTAL MONEY
)
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_ID_VENDAS
FOREIGN KEY(ID_VENDA) REFERENCES VENDAS(ID_VENDAS)
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_ID_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
GO

CREATE TABLE ENDERECO(
    ID_ENDERECO INT IDENTITY(1,1) PRIMARY KEY,
    RUA VARCHAR(60),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(30),
    CIDADE VARCHAR(30),
    CEP CHAR(8)
)

