CREATE TRIGGER trg_AjustaEstoque
ON [ITENS VENDAS]
AFTER INSERT 
AS 
    BEGIN
        UPDATE P
        SET P.[QTD ESTOQUE] = P.[QTD ESTOQUE] - I.QUANTIDADE
        FROM PRODUTOS P
        INNER JOIN INSERTED I ON P.ID_PRODUTO = I.ID_PRODUTO
    END;
GO