/* Filtro lucro por dia*/
SELECT DATA_VENDA, SUM(VALOR_TOTAL) AS LUCRO 
FROM VENDAS
GROUP BY DATA_VENDA
GO


/* Filtrando por mês */
SELECT FORMAT(DATA_VENDA, 'yyyy-MM') AS MES_VENDA,
    SUM(VALOR_TOTAL) AS LUCRO
FROM VENDAS
GROUP BY FORMAT(DATA_VENDA, 'yyyy-MM')
ORDER BY MES_VENDA;
GO