/* Contagem de produtos vendidos por categoria */
SELECT C.CATEGORIA, SUM(IV.QUANTIDADE) AS TOTAL_VENDIDO
FROM CATEGORIAS C
JOIN PRODUTOS P ON C.ID_CATEGORIA = P.ID_CATEGORIA
JOIN [ITENS VENDAS] IV ON P.ID_PRODUTO = IV.ID_PRODUTO
GROUP BY C.CATEGORIA

/* lista as vendas cujo valor total foi maior que a média */
SELECT ID_VENDAS, VALOR_TOTAL
FROM VENDAS 
WHERE VALOR_TOTAL > (SELECT AVG(VALOR_TOTAL) FROM VENDAS);