CREATE DATABASE [NEXTPLAY FISICA]
GO

USE [NEXTPLAY FISICA]
	
CREATE TABLE FORNECEDORES(
	ID_FORNECEDOR INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	CNPJ CHAR(14) UNIQUE NOT NULL,
	TELEFONE VARCHAR(30) NOT NULL,
	ID_ENDERECO INT
)
GO

CREATE TABLE PRODUTOS(
    ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    CATEGORIA VARCHAR(30) NOT NULL,
    PRECO MONEY NOT NULL,
    [QTD ESTOQUE] INT NOT NULL,
    MARCA VARCHAR(30) NOT NULL
)
GO

CREATE TABLE CATEGORIAS(
    ID_CATEGORIAS INT IDENTITY(1,1) PRIMARY KEY,
    CATEGORIA VARCHAR(30) NOT NULL
)
GO

ALTER TABLE PRODUTOS ADD CONSTRAINT FK_ID_CATEGORIA
FOREIGN KEY(CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIAS)
GO


CREATE TABLE [GASTOS MENSAIS](
    ID_GASTOS INT IDENTITY(1,1) PRIMARY KEY,
    SALARIOS MONEY NOT NULL,
    [COMPRA ESTOQUE] MONEY NOT NULL
)
GO

CREATE  TABLE CLIENTES(
    ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    [TOTAL GASTO] MONEY NOT NULL,
    ID_ENDERECO INT
)
GO

ALTER TABLE CLIENTES ADD CONSTRAINT FK_ID_ENDERECO
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
GO

CREATE TABLE VENDAS(
    ID_VENDAS INT IDENTITY(1,1) PRIMARY KEY,
    [VALOR TOTAL] MONEY NOT NULL,
    [METODO PAGAMENTO] VARCHAR(30) NOT NULL,
    [DATA VENDA] DATE NOT NULL,
    ID_CLIENTES INT
)
GO

ALTER TABLE VENDAS ADD CONSTRAINT FK_ID_CLIENTES
FOREIGN KEY(ID_CLIENTES) REFERENCES CLIENTES(ID_CLIENTE)
GO


CREATE TABLE [ITENS VENDAS](
    ID_ITEM_VENDA INT IDENTITY(1,1) PRIMARY KEY,
    ID_VENDA INT ,
    ID_PRODUTO INT,
    QUANTIDADE INT,
    [PRECO UNITARIO] MONEY,
    SUBTOTAL MONEY
)
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_ID_VENDAS
FOREIGN KEY(ID_VENDA) REFERENCES VENDAS(ID_VENDAS)
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_ID_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
GO

CREATE TABLE ENDERECO(
    ID_ENDERECO INT IDENTITY(1,1) PRIMARY KEY,
    RUA VARCHAR(60) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    CEP CHAR(8) NOT NULL
)
GO
