CREATE DATABASE [NEXTPLAY ECOMMERCE]

CREATE TABLE PRODUTOS(
    ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    CATEGORIA VARCHAR(30) NOT NULL,
    PRECO MONEY NOT NULL,
    [QTD ESTOQUE] INT NOT NULL,
    MARCA VARCHAR(30) NOT NULL
)
GO


CREATE TABLE [GASTOS MENSAIS](
ID_GASTOS INT,
SALARIOS MONEY,
MARKETING MONEY,
[HOSPEDAGEM ONLINE] MONEY
)
GO

CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(15)NOT NULL,
EMAIL VARCHAR(60)NOT NULL,
[TOTAL GASTO] MONEY NOT NULL,
ID_ENDERECO INT 
)
GO

CREATE TABLE VENDAS(
ID_VENDAS INT IDENTITY(1,1) PRIMARY KEY,
[VALOR TOTAL] MONEY NOT NULL,
[METODO PAGAMENTO] VARCHAR(20) NOT NULL,
[DATA VENDA] DATE NOT NULL,
ID_CLIENTES INT
)
GO

CREATE TABLE [ITENS VENDAS](
	ID_ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_VENDAS INT,
	ID_PRODUTO INT,
	QUANTIDADE INT NOT NULL,
	[PRECO UNITARIO] MONEY NOT NULL,
	SUBTOTAL MONEY NOT NULL
)
GO

CREATE TABLE ENDERECO(
ID_ENDERECO INT IDENTITY(1,1) PRIMARY KEY,
RUA VARCHAR(60),
NUMERO VARCHAR(10),
COMPLEMENTO VARCHAR(30),
CIDADE VARCHAR(30),
CEP CHAR(8)
)
GO

CREATE TABLE FEEDBACK(
ID_FEEDBACK INT IDENTITY(1,1) PRIMARY KEY,
ID_CLIENTE INT,
[NOTA AVALIACAO] INT,
COMENTARIO TEXT,
DATA DATE
)
GO

ALTER TABLE CLIENTES ADD CONSTRAINT FK_ID_ENDERECO
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
GO

ALTER TABLE VENDAS ADD CONSTRAINT FK_ID_CLIENTES
FOREIGN KEY(ID_CLIENTES) REFERENCES CLIENTES(ID_CLIENTE)
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_ID_VENDAS
FOREIGN KEY(ID_VENDAS) REFERENCES VENDAS(ID_VENDAS)
GO

ALTER TABLE [ITENS VENDAS]
ADD CONSTRAINT FK_ID_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
GO
