-- Desativar a restrição TABELA PRODUTOS
ALTER TABLE [dbo].[ITENS VENDAS] NOCHECK CONSTRAINT [FK_ID_PRODUTO];

-- Reativar a restrição
ALTER TABLE [dbo].[ITENS VENDAS] CHECK CONSTRAINT [FK_ID_PRODUTO];

-- -- Desativar a restrição TABELA VENDAS
ALTER TABLE [dbo].[ITENS VENDAS] NOCHECK CONSTRAINT [FK_ID_VENDAS];

-- -- Reativar a restrição TABELA VENDAS
ALTER TABLE [dbo].[ITENS VENDAS] CHECK CONSTRAINT [FK_ID_PRODUTO];  



CREATE INDEX idx_valor_total
ON VENDAS(VALOR_TOTAL)
INCLUDE (METODO_PAGAMENTO, DATA_VENDA, ID_CLIENTE)
GO


SELECT * FROM VENDAS
WHERE VALOR_TOTAL > 4500
GO
