CREATE TRIGGER atualizarEstoque
ON [NEXTPLAY ECOMMERCE].dbo.[ITENS VENDAS]
AFTER INSERT 
AS
BEGIN
    -- Atualizar o estoque na base de dados da loja física
    UPDATE [NEXTPLAY FISICA].dbo.PRODUTOS
    SET QTD_ESTOQUE = QTD_ESTOQUE - i.QUANTIDADE
    FROM [NEXTPLAY FISICA].dbo.PRODUTOS p
    INNER JOIN inserted i ON p.ID_PRODUTO = i.ID_PRODUTO
END


CREATE TRIGGER trg_AjustaEstoque
ON [ITENS VENDAS]
AFTER INSERT 
AS 
    BEGIN
        UPDATE P
        SET P.QTD_ESTOQUE = P.QTD_ESTOQUE - I.QUANTIDADE
        FROM PRODUTOS P
        INNER JOIN INSERTED I ON P.ID_PRODUTO = I.ID_PRODUTO
    END;
GO
