CREATE DATABASE [NEXTPLAY ECOMMERCE]
GO

USE [NEXTPLAY ECOMMERCE]

GO

CREATE TABLE ENDERECO(
    ID_ENDERECO INT PRIMARY KEY,
    RUA VARCHAR(60) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    CEP CHAR(9) NOT NULL
)
GO

CREATE  TABLE CLIENTES(
    ID_CLIENTE INT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    TOTAL_GASTO MONEY NOT NULL,
    ID_ENDERECO INT
)
GO

ALTER TABLE CLIENTES ADD CONSTRAINT FK_ID_ENDERECO
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO)
GO

CREATE TABLE PRODUTOS(
    ID_PRODUTO INT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL UNIQUE,
    DESCRICAO TEXT NOT NULL,
    PRECO MONEY NOT NULL,
    QTD_ESTOQUE INT NOT NULL,
	ID_CATEGORIA INT NOT NULL
)
GO

CREATE TABLE CATEGORIAS(
    ID_CATEGORIA INT PRIMARY KEY,
    CATEGORIA VARCHAR(30) NOT NULL
)
GO

ALTER TABLE PRODUTOS ADD CONSTRAINT FK_ID_CATEGORIA
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
GO

CREATE TABLE VENDAS(
    ID_VENDAS INT PRIMARY KEY,
    VALOR_TOTAL MONEY NOT NULL,
    METODO_PAGAMENTO VARCHAR(30) NOT NULL,
    DATA_VENDA DATE NOT NULL,
    ID_CLIENTE INT
)
GO

ALTER TABLE VENDAS ADD CONSTRAINT FK_ID_CLIENTES
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
GO

CREATE TABLE [ITENS VENDAS](
    ID_ITEM_VENDA INT PRIMARY KEY,
    ID_VENDA INT ,
    ID_PRODUTO INT,
    QUANTIDADE INT,
    PRECO_UNITARIO MONEY,
    SUBTOTAL MONEY
)
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_ID_VENDAS
FOREIGN KEY(ID_VENDA) REFERENCES VENDAS(ID_VENDAS)
GO


ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_ID_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
GO

CREATE TABLE [GASTOS MENSAIS](
    ID_GASTOS INT PRIMARY KEY,
    SALARIOS MONEY NOT NULL,
    MARKETING MONEY NOT NULL,
	HOSPEDAGEM MONEY NOT NULL
)
GO

CREATE TABLE FEEDBACK(
ID_FEEDBACK INT PRIMARY KEY,
ID_CLIENTE INT,
NOTA_AVALIACAO INT,
COMENTARIO TEXT,
DATA DATE
)
GO

